# Config for futher replies of the bot, if there was no content generated so far

import _ from 'lodash'
import base from '..' # The base config
import { seed } from '~/plugins/magic/utils'

previousExchange = [{
  query: 'Meaning of life'
  reply: "The meaning of life is **finding joy** in the little things, **growing your understanding** of the world around you, and **connecting with others** by **supporting each other** and **exploring the world together**.\n\nOh, and it’s also **42** ;-)"
}]

markmap = """
  # Meaning of life
  ## Finding joy
  ## Growing your understanding
  ## Connecting with others
  ### Supporting each other
  ### Exploring the world together
  ## 42
"""

export plainWithoutExamples = -> _.merge base(), {
  specs:
    accepts:
      previousExchange: "An arary of query-reply objects."
      markmap: 'The latest mindmap generated by Mindy, in markmap format.'
      query: 'The user’s new query.'
    returns:
      markmap: 'An updated mindmap, in markmap format.'
}

input = (query) ->
  input: {
    ...seed()
    previousExchange
    markmap
    query
  }

export default -> _.merge plainWithoutExamples(), {
  examples: [
    {
      ...input '42?'
      output: {
        thoughts: 'Oh, I guess they didn’t get the reference. Let me add some more context to the mindmap.'
        content: null
        reply: "Oh. That’s a reference to Douglas Adams’s classic humor/science fiction novel, *Hitchhiker’s Guide to the Galaxy*.\n\nIt says the answer to the ultimate question of life, the universe, and everything is 42."
        markmap: """
          #{markmap}
          ### Hitchhiker’s Guide to the Galaxy
          #### Douglas Adams, 1979
          #### Classic of humor and science fiction
          #### The answer to the ultimate question of life, the universe, and everything is 42
        """
      }
    }, {
      ...input 'Can you write a blog post about it?'
      output:
        thoughts: 'Good idea. Let’s start with a short introduction to the topic and an outline to fill in later and a mindmap to make some creative decisions.'
        content:
          type: 'text'
          language: 'markdown'
          title: 'Blog post: Meaning of life'
        reply: "Sure, give me a sec. Here’s a short introduction to the topic. I also updated the mindmap so we can think of how to approach the topic."
        markmap: """
          #{markmap}
          ## Blog post
          ### Approaches
          #### Listicle
          #### Essay
          #### Narrative
          ### Research
          #### Sources
          #### Citations
          #### Personal experience
          ### Mood
          #### Humorous
          #### Serious
          #### Neutral
        """
    }
  ]
}