export seed = -> { seed: _.random(100, 999)}

export accepts =
  previousExchange: "array of query-reply objects."
  markmap: 'The latest mindmap generated by Mindy, in markmap format.'
  code: 'Previously generated code'
  language: 'Language in which the code is written.'
  text: 'Previously generated text'
  format: 'Format of the previously generated text'
  query: 'The user’s new query.'

export returns =
  updatedCode: 'Updated code based on the previous exchange and context.'
  updatedLanguage: 'Language in which the updated code is written (can be the same as the previous language).' 
  updatedText: 'Updated text based on the previous exchange and context.'
  updatedFormat: 'Format of the updated text (can be the same as the previous format).'